name: Build and Deploy to Cloud Run

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'astro/**'
  workflow_dispatch:

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          astro:
            - 'astro/**'

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: |-
        gcloud auth configure-docker

    - name: Build and Push Docker image Frontend
      if: steps.filter.outputs.astro == 'true'
      run: |-
        gcloud builds submit --quiet --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}:$GITHUB_SHA ./astro

    - name: Deploy to Cloud Run Frontend
      if: steps.filter.outputs.astro == 'true'
      run: |-
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}:$GITHUB_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory=512M \
          --cpu=1 \
          --concurrency=150 \
          --timeout=300 \
          --max-instances=1 \
        

    